# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/phung/Documents/fpga_overlay/riffa/fpga/xilinx/vc707/VC707_Gen2x8If128/ip/PCIeGen2x8If128.xci
# IP: The module: 'PCIeGen2x8If128' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/phung/Documents/fpga_overlay/riffa/fpga/xilinx/vc707/VC707_Gen2x8If128/ip/source/PCIeGen2x8If128-PCIE_X1Y0.xdc
# XDC: The top module name and the constraint reference have the same name: 'PCIeGen2x8If128'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/phung/Documents/fpga_overlay/riffa/fpga/xilinx/vc707/VC707_Gen2x8If128/ip/synth/PCIeGen2x8If128_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PCIeGen2x8If128'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/phung/Documents/fpga_overlay/riffa/fpga/xilinx/vc707/VC707_Gen2x8If128/ip/PCIeGen2x8If128.xci
# IP: The module: 'PCIeGen2x8If128' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/phung/Documents/fpga_overlay/riffa/fpga/xilinx/vc707/VC707_Gen2x8If128/ip/source/PCIeGen2x8If128-PCIE_X1Y0.xdc
# XDC: The top module name and the constraint reference have the same name: 'PCIeGen2x8If128'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/phung/Documents/fpga_overlay/riffa/fpga/xilinx/vc707/VC707_Gen2x8If128/ip/synth/PCIeGen2x8If128_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PCIeGen2x8If128'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
