# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7vx485tffg1761-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/phung/Documents/fpga_overlay/riffa/fpga/xilinx/vc707/VC707_Gen2x8If128/prj/VC707_Gen2x8If128.cache/wt [current_project]
set_property parent.project_path /home/phung/Documents/fpga_overlay/riffa/fpga/xilinx/vc707/VC707_Gen2x8If128/prj/VC707_Gen2x8If128.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:vc707:part0:1.1 [current_project]
set_property ip_cache_permissions disable [current_project]
read_verilog {
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/widths.vh
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/riffa.vh
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/ultrascale.vh
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/types.vh
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/trellis.vh
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/xilinx.vh
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/tlp.vh
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/schedules.vh
}
read_verilog -library xil_defaultlib -sv /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/functions.vh
set_property file_type SystemVerilog [get_files /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/functions.vh]
read_verilog -library xil_defaultlib {
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/async_fifo.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/async_fifo_fwft.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/channel.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/channel_128.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/channel_32.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/channel_64.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/chnl_tester.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/counter.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/cross_domain_signal.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/demux.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/engine_layer.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/ff.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/fifo.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/fifo_packer_128.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/fifo_packer_32.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/fifo_packer_64.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/interrupt.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/interrupt_controller.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/mux.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/offset_flag_to_one_hot.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/offset_to_mask.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/one_hot_mux.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/pipeline.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/ram_1clk_1w_1r.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/ram_2clk_1w_1r.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/recv_credit_flow_ctrl.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/register.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/registers.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/reorder_queue.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/reorder_queue_input.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/reorder_queue_output.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/reset_controller.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/reset_extender.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/riffa.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/xilinx/vc707/riffa_wrapper_vc707.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/rotate.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/rx_engine_classic.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/rx_engine_ultrascale.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/rx_port_128.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/rx_port_32.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/rx_port_64.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/rx_port_channel_gate.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/rx_port_reader.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/rx_port_requester_mux.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/rxc_engine_128.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/rxc_engine_classic.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/rxc_engine_ultrascale.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/rxr_engine_128.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/rxr_engine_classic.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/rxr_engine_ultrascale.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/scsdpram.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/sg_list_reader_128.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/sg_list_reader_32.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/sg_list_reader_64.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/sg_list_requester.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/shiftreg.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/sync_fifo.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/syncff.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/translation_xilinx.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/tx_alignment_pipeline.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/tx_data_fifo.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/tx_data_pipeline.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/tx_data_shift.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/tx_engine.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/tx_engine_classic.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/tx_engine_selector.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/tx_engine_ultrascale.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/tx_hdr_fifo.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/tx_multiplexer.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/tx_multiplexer_128.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/tx_multiplexer_32.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/tx_multiplexer_64.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/tx_port_128.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/tx_port_32.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/tx_port_64.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/tx_port_buffer_128.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/tx_port_buffer_32.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/tx_port_buffer_64.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/tx_port_channel_gate_128.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/tx_port_channel_gate_32.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/tx_port_channel_gate_64.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/tx_port_monitor_128.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/tx_port_monitor_32.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/tx_port_monitor_64.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/tx_port_writer.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/txc_engine_classic.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/txc_engine_ultrascale.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/txr_engine_classic.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/riffa_hdl/txr_engine_ultrascale.v
  /home/phung/Documents/fpga_overlay/riffa/fpga/xilinx/vc707/VC707_Gen2x8If128/hdl/VC707_Gen2x8If128.v
}
read_ip -quiet /home/phung/Documents/fpga_overlay/riffa/fpga/xilinx/vc707/VC707_Gen2x8If128/ip/PCIeGen2x8If128.xci
set_property used_in_implementation false [get_files -all /home/phung/Documents/fpga_overlay/riffa/fpga/xilinx/vc707/VC707_Gen2x8If128/ip/source/PCIeGen2x8If128-PCIE_X1Y0.xdc]
set_property used_in_implementation false [get_files -all /home/phung/Documents/fpga_overlay/riffa/fpga/xilinx/vc707/VC707_Gen2x8If128/ip/synth/PCIeGen2x8If128_ooc.xdc]
set_property is_locked true [get_files /home/phung/Documents/fpga_overlay/riffa/fpga/xilinx/vc707/VC707_Gen2x8If128/ip/PCIeGen2x8If128.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/phung/Documents/fpga_overlay/riffa/fpga/xilinx/vc707/VC707_Gen2x8If128/constr/VC707_Gen2x8If128.xdc
set_property used_in_implementation false [get_files /home/phung/Documents/fpga_overlay/riffa/fpga/xilinx/vc707/VC707_Gen2x8If128/constr/VC707_Gen2x8If128.xdc]


synth_design -top VC707_Gen2x8If128 -part xc7vx485tffg1761-2


write_checkpoint -force -noxdef VC707_Gen2x8If128.dcp

catch { report_utilization -file VC707_Gen2x8If128_utilization_synth.rpt -pb VC707_Gen2x8If128_utilization_synth.pb }
